# fly.toml app configuration file generated for codeportfolio on 2023-08-20T20:06:45+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "codeportfolio"
primary_region = "ams"

[build]
  image = "kamoragr/codeportfolio:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySetting__CloudName="duovczxpz"
  CloudinarySetting__ApiKey="893942848778852"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
